import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("login", "routes/login.tsx"),
  route("logout", "routes/logout.tsx"),
  route("api/logs/stream", "routes/api.logs.stream.ts"),
  route("api/llm-usage", "routes/api.llm-usage.ts"),
  route("api/backtest-config", "routes/api.backtest-config.ts"),
  route("api/backtest-trigger", "routes/api.backtest-trigger.ts"),
  route("api/trading-config", "routes/api.trading-config.ts"),
  route("api/trading-trigger", "routes/api.trading-trigger.ts"),
  route("api/llm-providers", "routes/api.llm-providers.ts"),
  route("api/strategy-presets", "routes/api.strategy-presets.ts"),
  route("api/strategy-presets/activate", "routes/api.strategy-presets.activate.ts"),
  route("api/strategy-presets/history", "routes/api.strategy-presets.history.ts"),
  route("dashboard", "routes/dashboard.tsx", [
    index("routes/dashboard._index.tsx"),
    route("chart", "routes/dashboard.chart.tsx"),
    route("decisions", "routes/dashboard.decisions.tsx"),
    route("decisions/:id", "routes/dashboard.decisions.$id.tsx"),
    route("positions", "routes/dashboard.positions.tsx"),
    route("analytics", "routes/dashboard.analytics.tsx"),
    route("llm-usage", "routes/dashboard.llm-usage.tsx"),
    route("backtest", "routes/dashboard.backtest.tsx"),
    route("backtest-settings", "routes/dashboard.backtest-settings.tsx"),
    route("logs", "routes/dashboard.logs.tsx"),
    route("alerts", "routes/dashboard.alerts.tsx"),
    route("control", "routes/dashboard.control.tsx"),
    route("settings", "routes/dashboard.settings.tsx"),
    route("strategy", "routes/dashboard.strategy.tsx"),
  ]),
] satisfies RouteConfig;
