import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("login", "routes/login.tsx"),
  route("logout", "routes/logout.tsx"),
  route("api/logs/stream", "routes/api.logs.stream.ts"),
  route("api/llm-usage", "routes/api.llm-usage.ts"),
  route("api/backtest-config", "routes/api.backtest-config.ts"),
  route("api/backtest-trigger", "routes/api.backtest-trigger.ts"),
  route("api/trading-config", "routes/api.trading-config.ts"),
  route("api/trading-trigger", "routes/api.trading-trigger.ts"),
  route("api/llm-providers", "routes/api.llm-providers.ts"),
  route("api/llm-config/providers", "routes/api.llm-config.providers.ts"),
  route("api/llm-config/routing", "routes/api.llm-config.routing.ts"),
  route("api/llm-config/models", "routes/api.llm-config.models.ts"),
  route("api/llm-config/test", "routes/api.llm-config.test.ts"),
  route("api/llm-config/oauth-auth", "routes/api.llm-config.oauth-auth.ts"),
  route("api/llm-config/oauth-status", "routes/api.llm-config.oauth-status.ts"),
  route("api/strategy-presets", "routes/api.strategy-presets.ts"),
  route("api/strategy-presets/activate", "routes/api.strategy-presets.activate.ts"),
  route("api/strategy-presets/lock", "routes/api.strategy-presets.lock.ts"),
  route("api/strategy-presets/history", "routes/api.strategy-presets.history.ts"),
  route("api/strategy-presets/suggest", "routes/api.strategy-presets.suggest.ts"),
  route("api/strategy-presets/update", "routes/api.strategy-presets.update.ts"),
  route("api/strategy-presets/save-as", "routes/api.strategy-presets.save-as.ts"),
  route("api/strategy-presets/reset", "routes/api.strategy-presets.reset.ts"),
  route("api/strategy-presets/delete", "routes/api.strategy-presets.delete.ts"),
  route("api/strategy-presets/defaults", "routes/api.strategy-presets.defaults.ts"),
  route("api/advisory", "routes/api.advisory.ts"),
  route("api/advisory-action", "routes/api.advisory-action.ts"),
  route("api/advisory-trigger", "routes/api.advisory-trigger.ts"),
  route("api/advisory-settings", "routes/api.advisory-settings.ts"),
  route("api/notification-settings", "routes/api.notification-settings.ts"),
  route("api/event-triggers/logs", "routes/api.event-triggers.logs.ts"),
  route("api/event-triggers/config", "routes/api.event-triggers.config.ts"),
  route("api/event-triggers/mapping", "routes/api.event-triggers.mapping.ts"),
  route("api/account-state", "routes/api.account-state.ts"),
  route("api/change-password", "routes/api.change-password.ts"),
  route("dashboard", "routes/dashboard.tsx", [
    index("routes/dashboard._index.tsx"),
    route("chart", "routes/dashboard.chart.tsx"),
    route("decisions", "routes/dashboard.decisions.tsx"),
    route("decisions/:id", "routes/dashboard.decisions.$id.tsx"),
    route("positions", "routes/dashboard.positions.tsx"),
    route("analytics", "routes/dashboard.analytics.tsx"),
    route("llm-usage", "routes/dashboard.llm-usage.tsx"),
    route("backtest", "routes/dashboard.backtest.tsx"),
    route("backtest-settings", "routes/dashboard.backtest-settings.tsx"),
    route("logs", "routes/dashboard.logs.tsx"),
    route("alerts", "routes/dashboard.alerts.tsx"),
    route("control", "routes/dashboard.control.tsx"),
    route("settings", "routes/dashboard.settings.tsx"),
    route("strategy", "routes/dashboard.strategy.tsx"),
    route("advisory", "routes/dashboard.advisory.tsx"),
    route("advisory-settings", "routes/dashboard.advisory-settings.tsx"),
    route("notification-settings", "routes/dashboard.notification-settings.tsx"),
    route("event-triggers", "routes/dashboard.event-triggers.tsx"),
  ]),
] satisfies RouteConfig;
