"""系统内置策略预设模板"""

from ..models.strategy_preset import StrategyPreset, StrategyPresetConfig

SYSTEM_PRESETS: list[StrategyPreset] = [
    StrategyPreset(
        name="steady_trend",
        display_name="稳健趋势",
        description="跟随明确趋势，低频交易，严格风控",
        category="trend",
        risk_level="low",
        config=StrategyPresetConfig(
            enabled_strategies=["trend_following"],
            strategy_weights={"trend_following": 1.0},
            ai_weight=0.6,
            quant_weight=0.4,
            sentiment_weight=0.2,
            timeframes=["1h", "4h"],
            min_trade_interval_seconds=21600,
            stop_loss_atr_multiplier=3.0,
            take_profit_atr_multiplier=8.0,
            max_position_pct=15.0,
            enable_pyramid=False,
            max_pyramid_times=0,
            enable_sentiment=True,
            min_profit_threshold=0,
            use_market_order_only=False,
        ),
    ),
    StrategyPreset(
        name="aggressive_trend",
        display_name="激进趋势",
        description="强趋势市场积极跟进，允许加仓放大收益",
        category="trend",
        risk_level="medium_high",
        config=StrategyPresetConfig(
            enabled_strategies=["trend_following", "breakout"],
            strategy_weights={"trend_following": 0.7, "breakout": 0.3},
            ai_weight=0.4,
            quant_weight=0.6,
            sentiment_weight=0,
            timeframes=["15m", "1h"],
            min_trade_interval_seconds=7200,
            stop_loss_atr_multiplier=2.0,
            take_profit_atr_multiplier=5.0,
            max_position_pct=30.0,
            enable_pyramid=True,
            max_pyramid_times=2,
            enable_sentiment=False,
            min_profit_threshold=0,
            use_market_order_only=False,
        ),
    ),
    StrategyPreset(
        name="range_harvest",
        display_name="震荡收割",
        description="区间震荡市场高抛低吸，均值回归为主",
        category="range",
        risk_level="medium",
        config=StrategyPresetConfig(
            enabled_strategies=["mean_reversion", "trend_following"],
            strategy_weights={"mean_reversion": 0.8, "trend_following": 0.2},
            ai_weight=0.3,
            quant_weight=0.7,
            sentiment_weight=0.2,
            timeframes=["15m", "1h"],
            min_trade_interval_seconds=7200,
            stop_loss_atr_multiplier=2.0,
            take_profit_atr_multiplier=3.0,
            max_position_pct=20.0,
            enable_pyramid=False,
            max_pyramid_times=0,
            enable_sentiment=True,
            min_profit_threshold=0,
            use_market_order_only=False,
        ),
    ),
    StrategyPreset(
        name="breakout_hunter",
        display_name="突破猎手",
        description="捕捉盘整后的突破行情，配合趋势确认",
        category="breakout",
        risk_level="medium",
        config=StrategyPresetConfig(
            enabled_strategies=["breakout", "trend_following"],
            strategy_weights={"breakout": 0.8, "trend_following": 0.2},
            ai_weight=0.4,
            quant_weight=0.6,
            sentiment_weight=0.2,
            timeframes=["1h", "4h"],
            min_trade_interval_seconds=14400,
            stop_loss_atr_multiplier=2.5,
            take_profit_atr_multiplier=6.0,
            max_position_pct=25.0,
            enable_pyramid=True,
            max_pyramid_times=1,
            enable_sentiment=True,
            min_profit_threshold=0,
            use_market_order_only=False,
        ),
    ),
    StrategyPreset(
        name="mild_scalping",
        display_name="温和剥头皮",
        description="中频小利润交易，均值回归主导，适合震荡和趋势市",
        category="scalping",
        risk_level="medium_low",
        config=StrategyPresetConfig(
            enabled_strategies=["mean_reversion", "trend_following"],
            strategy_weights={"mean_reversion": 0.6, "trend_following": 0.4},
            ai_weight=0.25,
            quant_weight=0.75,
            sentiment_weight=0,
            timeframes=["5m", "15m"],
            min_trade_interval_seconds=900,
            stop_loss_atr_multiplier=1.5,
            take_profit_atr_multiplier=2.0,
            max_position_pct=10.0,
            enable_pyramid=False,
            max_pyramid_times=0,
            enable_sentiment=False,
            min_profit_threshold=0.15,
            use_market_order_only=False,
        ),
    ),
    StrategyPreset(
        name="aggressive_scalping",
        display_name="激进剥头皮",
        description="高频快进快出，几乎纯量化驱动，薄利多销",
        category="scalping",
        risk_level="medium",
        config=StrategyPresetConfig(
            enabled_strategies=["mean_reversion", "trend_following", "breakout"],
            strategy_weights={"mean_reversion": 0.5, "trend_following": 0.3, "breakout": 0.2},
            ai_weight=0.1,
            quant_weight=0.9,
            sentiment_weight=0,
            timeframes=["1m", "5m"],
            min_trade_interval_seconds=300,
            stop_loss_atr_multiplier=1.0,
            take_profit_atr_multiplier=1.5,
            max_position_pct=8.0,
            enable_pyramid=False,
            max_pyramid_times=0,
            enable_sentiment=False,
            min_profit_threshold=0.1,
            use_market_order_only=True,
        ),
    ),
    StrategyPreset(
        name="balanced_conservative",
        display_name="均衡保守",
        description="AI主导决策，低仓位低频率，适合不确定市场",
        category="balanced",
        risk_level="lowest",
        config=StrategyPresetConfig(
            enabled_strategies=["trend_following", "mean_reversion", "breakout"],
            strategy_weights={"trend_following": 0.5, "mean_reversion": 0.3, "breakout": 0.2},
            ai_weight=0.7,
            quant_weight=0.3,
            sentiment_weight=0.2,
            timeframes=["4h", "1d"],
            min_trade_interval_seconds=43200,
            stop_loss_atr_multiplier=4.0,
            take_profit_atr_multiplier=6.0,
            max_position_pct=10.0,
            enable_pyramid=False,
            max_pyramid_times=0,
            enable_sentiment=True,
            min_profit_threshold=0,
            use_market_order_only=False,
        ),
    ),
]


def get_preset_by_name(name: str) -> StrategyPreset | None:
    """Get a system preset by name."""
    for preset in SYSTEM_PRESETS:
        if preset.name == name:
            return preset
    return None


def get_all_system_defaults() -> dict[str, dict]:
    """Return all system preset default configs keyed by name."""
    return {p.name: p.config.model_dump() for p in SYSTEM_PRESETS}


DEFAULT_PRESET_NAME = "steady_trend"
